substitutions:
  _REGION: southamerica-east1
  _REPO: crescebr

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    id: build-backend
    args:
      - build
      - -f
      - backend/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/backend:latest
      - .

  - name: gcr.io/cloud-builders/docker
    id: build-frontend
    args:
      - build
      - -f
      - frontend/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/frontend:latest
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/backend:latest
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/frontend:latest
