export default {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.test.ts'],
  setupFilesAfterEnv: ['<rootDir>/src/__tests__/setup.ts'],
  testTimeout: 30000,
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/server.ts',
    '!src/config/**',
    '!src/models/index.ts',
    '!src/routes/**',
    '!src/__tests__/setup.ts',
    '!src/__tests__/integration/**',
    '!src/types/**',
  ],
  coverageDirectory: 'coverage',
  verbose: true,
};
